# Generated by Django 6.0.1 on 2026-01-16 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(help_text='Reference to ShopCore User')),
                ('reference_id', models.UUIDField(blank=True, help_text='Reference to related entity (Order, Transaction, etc.)', null=True)),
                ('reference_type', models.CharField(blank=True, choices=[('order', 'Order'), ('transaction', 'Transaction'), ('shipment', 'Shipment'), ('product', 'Product'), ('other', 'Other')], max_length=20, null=True)),
                ('issue_type', models.CharField(choices=[('order', 'Order Issue'), ('delivery', 'Delivery Issue'), ('payment', 'Payment Issue'), ('refund', 'Refund Request'), ('product', 'Product Issue'), ('account', 'Account Issue'), ('general', 'General Inquiry'), ('complaint', 'Complaint'), ('feedback', 'Feedback')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting on Customer'), ('waiting_internal', 'Waiting on Internal Team'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assigned_agent_id', models.UUIDField(blank=True, help_text='Support agent assigned to ticket', null=True)),
                ('assigned_agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'caredesk_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1-5')),
                ('comments', models.TextField(blank=True, null=True)),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='caredesk.ticket')),
            ],
            options={
                'verbose_name': 'Satisfaction Survey',
                'verbose_name_plural': 'Satisfaction Surveys',
                'db_table': 'caredesk_satisfaction_surveys',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(choices=[('user', 'Customer'), ('agent', 'Support Agent'), ('system', 'System')], max_length=10)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes not visible to customer')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='caredesk.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'db_table': 'caredesk_ticket_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
